### PR TITLE
Copy unit test from pgcli

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Copy unit test from pgcli

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by meeuw** [comment]
This seems to be an issue in tabulate:
https://bitbucket.org/astanin/python-tabulate/pull-requests/42/add-test-for-wide-characters-in-header/diff

**Comment by meeuw** [comment]
I've created a PR for python-tabulate to fix this issue at:
https://bitbucket.org/astanin/python-tabulate/pull-requests/44

**Comment by tsroten** [comment]
@meeuw I'm assuming we should wait to merge this until the tabulate update is released, right?

**Comment by meeuw** [comment]
Yes please :smile: 

Maybe we should copy/move more like these tests from mycli and pgcli to cli_helpers...

**Comment by tsroten** [comment]
Thanks @meeuw!

**Pull request merged**
