### PR TITLE
Escape newline characters in plain-text table formatters

### PR DESCRIPTION
**Pull request by pasenor**
## Description
Escape `\n` and `\r` in plain-text formatters (those than do not draw lines between rows).
Otherwise a stand-alone `\r` breaks terminaltables (see [this issue](https://github.com/dbcli/mycli/issues/868)), and newline characters (`\n` or `\r\n`)  produce an ambiguous line with empty cells.

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by laixintao** [comment]
It seems that the official mysql client didn't handle that very well either 😏

mycli latest version:
image

mysql:
image

**Comment by laixintao** [comment]
CI was fixed here: https://github.com/dbcli/cli_helpers/pull/61/commits/02b56e2f89f7026d35b4fc3833e379b392bbf423

**Comment by laixintao** [comment]
@j-bennet I think we need a new release for this :)

**Comment by pasenor** [comment]
Or we could change the process for mycli and pgcli: make the master branch depend on a specific commit of cli_helpers, then before release switch to the appropriate version. Otherwise we need a release for every commit here :)

**Comment by laixintao** [comment]
> Or we could change the process for mycli and pgcli: make the master branch depend on a specific commit of cli_helpers, then before release switch to the appropriate version. Otherwise we need a release for every commit here :)

Does that mean `pip install mycli` need to install cli_helpers from Github? I personally don't like that, install from PyPI mirrors cloud have problems with GitHub, (especially in China).

Can we let the CI do the release job? For every master commit, build and upload a new PyPI release. I do that in iredis(example: https://github.com/laixintao/iredis/runs/703470008 ) but only release for tags on mater.

For cli_helpers' version, we can use something like that: `0.8.dev3+rev4fa254c`. https://github.com/smessmer/gitversion

**Comment by pasenor** [comment]
No, I mean that `pip install mycli` would install everything from pypi as always.
However, in the master branch before release, we can happily depend on whatever commit we like (so `pip install git+https://github.com/dbcli/mycli.git@master` would install a specific commit of cli_helpers).
The release procedure is then
1. release cli_helpers to pypi
2. Set the correct version tag in mycli dependencies 
3. release mycli to pypi

It would require some additional checks in CI to prevent us from accidentally releasing mycli that depends on unreleased cli_helpers.

Or indeed release every commit automatically, don't see any problem with that. @amjith, I think you had some reservations against releasing too often?

**Comment by laixintao** [comment]
Both look good to me :)

**Comment by j-bennet** [comment]
Let's not make the release process more complicated than it needs to be. It's easy enough to release a new version of `cli_helpers` - we don't need to release on any commit. In mycli or pgcli, you only want to bump `cli_helpers` when you're explicitly using a new helpers' feature in application code. Otherwise `cli_helpers>=x.x.x` is fine.

**Comment by j-bennet** [comment]
2.0.1 is released.

**Pull request merged**
