### PR TITLE
Add package name to task entrypoints in setup.py

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Add package name to task entrypoints in setup.py

Could you please have a look @tsroten?

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
@meeuw I'm kind of confused about this. `cli_helpers` is not a package in this case. `tasks` is a module with no direct parent package. In order for `cli_helpers` to be a package, we'd need an `__init__.py` in the project directory (which we don't want).

Let's try to find out more about the problem.

**Comment by meeuw** [comment]
I've moved `tasks.py` to the `cli_helpers` package, that seems to work... I'm not sure how you think about that.

**Comment by tsroten** [comment]
@meeuw Oh, I see now. Yeah, I'm not sure development-related tasks should be in the `cli_helpers` package.

What do you think?

**Comment by tsroten** [comment]
@meeuw Maybe `entry_points` is not the right place for our development-related tasks.

Maybe we should use something like https://github.com/pyinvoke/invoke

**Comment by tsroten** [comment]
Setuptools describes entry points as:
> Entry points are used to support dynamic discovery of services or plugins provided by a project.

We definitely aren't using `tasks.py` to "provid[e]" services or plugins for public consumption.

I'll play around with invoke to see if it looks promising.

**Comment by meeuw** [comment]
I don't think it would really hurt to have our tasks exposed to the public, but it's indeed a bit weird, I'd rather use @amjith's pk instead of pyinvoke...

**Comment by tsroten** [comment]
@meeuw Good point. @amjith Is the ability to add custom commands to pk part of your plan?

**Comment by amjith** [comment]
> I'd rather use @amjith's pk

As flattered as I am, I would call `pk` an alpha-quality software with no tests and nearly zero docs. Just setting realistic expectations. :)

**Comment by amjith** [comment]
@tsroten Yes. Adding custom commands is already implemented.

**Pull request closed without merging**
