### PR TITLE
Move strip_ansi from tests.utils to cli_helpers.utils

### LINKED ISSUE #41: Move strip_ansi to main utils
It is useful to be able to strip the ansi emitted by other cli tools, in order to parse the output.

@coala needs something like that for https://github.com/coala/coala/issues/5281 , and we're looking for existing libraries which might do the trick for us.

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Move strip_ansi from tests.utils to cli_helpers.utils, fixes #41 

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Thanks @meeuw!!

**Comment by jayvdb** [comment]
Thank you.  Any chance of a release so this can be put into use... ? ;-)

**Comment by meeuw** [comment]
I'll ping @tsroten 😄

**Comment by tsroten** [comment]
@jayvdb @meeuw Version 1.0.2 is up [on PyPI](https://pypi.org/project/cli-helpers/) 😄

**Pull request merged**
