### PR TITLE
rename tsv to csv-tab, add new tsv output adapter

### PR DESCRIPTION
**Pull request by meeuw**
## Description
Rename old tsv format to csv-tab (because it add quotes), introduce new tsv output adapter.

More information about tsv: 
https://en.wikipedia.org/wiki/Tab-separated_values
(links to: https://www.iana.org/assignments/media-types/text/tab-separated-values)

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
@meeuw Hey Dick! Thanks for thinking about this. 

When I've seen a stripped down TSV format like this, there is no escaping at all, even for newlines (basically the idea is that TSV doesn't support any tabs or newlines in a field). Is the escaping of `\n` ideal here? It leads to things like this: `ab\r\\nc\t1\n`, where the CRLF is broken (that's taken from the unit tests).

What do you think?


Just for reference on the PR, here is the only "official", published TSV spec I can find: https://www.iana.org/assignments/media-types/text/tab-separated-values

**Comment by meeuw** [comment]
This is something I often use (and is now broken in mycli) for mysql `load data infile` and easy copy-pasting into a spreadsheet.

The tsv "specification" states: `Note that fields that contain tabs are not allowable in this encoding.`
(I think that also includes newlines)

So we need to escape or remove tabs/newlines, the official mysql client (in batch output) escapes these characters and this is also accepted for `load data infile`. Do you think we need an alternative output format, `tsv-strip` or `tsv-escape`?

**Comment by tsroten** [comment]
@meeuw I think it's fine as a `tsv` output. I like the idea of escaping both tabs and newlines (like MySQL).

As far as carriage returns go, I agree there is no need to escape them.

Nice work! I also like the `replace` helper 😄

**Comment by meeuw** [comment]
@tsroten thanks a lot for merging!

**Pull request merged**
