### PR TITLE
Add config file reading/writing

### PR DESCRIPTION
**Pull request by tsroten**
## Description

Adds config file reading. Client applications do not need to worry about where the config files are stored (unless they want to). Client applications can trust that the config files will be read safely and validated for the correct types/options. Booleans are booleans, integers are integers, etc.

A few notes:
- This uses the XDG spec for macOS and Linux. For Windows, it will respect the typically-recommended Windows locations for config files.
- This is easily extensible by client applications to add additional directories, customize the system directories, or change the user configuration file location.
- This supports config file validation using Configobj's validation library. It also converts values to the correct type (e.g. boolean, integer, etc.)

Current documentation for this: http://cli-helpers.readthedocs.io/en/feature-config/api.html#module-cli_helpers.config

**NOTE:** more documentation is being worked on for this.

## The Simplest Use Case
Here is the simplest use case, with no default config and no custom file locations:
```python
from cli_helpers.config import Config

config = Config('myapp', 'My Organization', 'config')
config.read()
```

## A Pretty Simple Use Case

Default config file:
```
[main]
# Default log level. Possible values: "CRITICAL", "ERROR", "WARNING", "INFO"
# and "DEBUG". "NONE" disables logging.
log_level = option('CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG', 'NONE', default='INFO')
```

Client code:
```python
import os

from cli_helpers.config import Config

PACKAGE_ROOT = os.path.dirname(__file__)

config = Config('mycli', 'dbcli', 'config', default=os.path.join(PACKAGE_ROOT, self.filename)
                validate=True)
config.read()

print(config['main']['log_level'])
```

In that case, the log level is guaranteed to be a valid option and it defaults to `'INFO'`.

## Default Config Values

Default values can be specified as a `dict` or as a path to a config file.
```python
config = Config('myapp', 'My Organization', 'config', default={'main': {'debug': False}})
```

```python
config = Config('myapp', 'My Organization', 'config', default='/path/to/default/file')
```

## Checklist

- [x] I've added this contribution to the `CHANGELOG`.
- [x] I've added my name to the `AUTHORS` file (or it's already there).

### CODE REVIEW

**Comment by tsroten** [comment]
Not sure why the code coverage isn't showing up on this PR, but it's still at 100%: https://codecov.io/gh/dbcli/cli_helpers/branch/feature%2Fconfig

**Comment by meeuw** [comment]
Hi Thomas, it looks all good, I'd like to know why you've chosen to split the code the way you did.
For example; would it be a good idea to merge:
- Config.read_default_config / Config.read
- Config._set_default / Config.__init__
- Config._raise_validation_errors / Config.read_default_config
- Config.all_config_files / Config.system_config_files / Config.additional_files
- Config.read / Config.all_config_files
- Config.read / Config.read_config_files

This would certainly improve readability, but if you already know all of these functions will directly used from mycli/pgcli/mssql-cli we should keep them (of course) seperate.

**Comment by tsroten** [comment]
@meeuw Thanks for the helpful feedback! I appreciate the good questions.

I personally prefer a maximum of two-to-three levels deep of conditional/loop indentation in functions, with large blocks of code within loops being split into functions, which is why some of that is broken out the way it is. I feel like it's easier to read indented code blocks when they are put in named functions.

I think some of the ones you mentioned make sense to merge. I'll try to rework these a bit so it's not as spread out:
- `_set_default` merged into `__init__`
- `_raise_validation_errors` into `read_default_config`

The other short file-based ones (`all_config_files`, `system_config_files`, `user_config_file`, and `additional_files`) make it very easy for client applications to override one or two pieces of the default configuration setup without affecting the rest. That might be my day-to-day Ruby programming shining through a bit.

Ultimately, my goal in this API was two-fold:
1. Make the default interface extremely easy-to-use (create a config object, then call `read()`).
2. Don't assume all client applications handle configuration the same way, so make it easy for them to customize various parts of the configuration process.

So, for number 1, we end up with one client-facing method that is the primary way to load the configuration -- `read()`.

For number 2, I tried to make it so client applications wouldn't have to replicate a whole lot of the logic if they want to override different portions of the config reading/writing:
- Which system config files to read
- Which user config file to read
- Which additional files to read (also controllable via the constructor)
- The reading of the files themselves
- The reading of the default config file (which might need different logic than the user-facing config files)
- The writing of the default config file
- The writing of the current, in-memory config to a file

**Comment by jayvdb** [comment]
Why not use https://github.com/ActiveState/appdirs to obtain the relevant directory paths when that is desired by the caller?

As Windows has so many changes to their dirs, you are begging for support problems by reimplementing this.

If `appdirs` doesnt provide the information in a usable way, maybe we can enhance appdirs so it does work for the needs of `dbcli` ...?

**Comment by amjith** [comment]
@jayvdb I believe the original reason was, we wanted a standard place to put our config files so we can tell users to go to a specific location on their computer and edit the config file. 

`appdirs` will give you the appropriate directory for the current operating system which is different for Windows 7, 8, 10 etc. Which makes our life harder when we want them to enable/disable a feature via the config file.

**Comment by jayvdb** [comment]
Ya, I guessed that, but you can use `appdirs` to give you the locations (any of them), and you choose which one you want to use.

It leads to better behaviour on flavours of Unix which you dont want to even know about, but their users are rather finicky about how apps work ;-)

**Comment by amjith** [comment]
The same reason applies to the Unix folks as well. We want our config files in a specific place so we can easily guide people there. 

We try to respect the standards wherever possible, for example, the config file used to go in the home folder ~/.pgclirc. We changed that to ~/.config/pgcli/config when we realized that it is disrespectful to litter the user's home folder. 

But we're trying to balance correctness and convenience. This is the best compromise we came up with, if you have examples of this being insufficient, I'm happy to consider it.

**Comment by tsroten** [comment]
`appdirs` is really pretty handy. @amjith is definitely right about balancing correctness and convenience.

Another specific use case is for macOS. In my experience, CLI apps users on Mac expect the config to behave like Linux (i.e. XDG). But, `appdirs` doesn't support XDG-based directories on macOS.

**Comment by tsroten** [comment]
@meeuw Okay, I've combined some of the functions together to make the logic more readable. Thanks!

I've kept some of them separate because I do think it will be helpful as a general-use API so that people can override the various behaviors as they need to.

**Comment by amjith** [comment]
Can we merge this PR and release a new version?

**Pull request merged**
